name: Build
on: push
jobs:
  build:
    name: Hugo Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out Source
        uses: actions/checkout@v4
      - name: Build the Site
        uses: docker://ghcr.io/gohugoio/hugo:v0.136.5
        with: { args: build }
